[package]
name = "nosql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7.3"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.39.3", features = ["full"] }
